### ISSUE TITLE
French link for exercise 1 not working

### ISSUE THREAD

**Issue by ricardoprins** [qiskit-community/ibm-quantum-challenge-2021#9]
The link to the French version's notebook file isn't working.

**Comment by HuangJunye** [comment]
@ricardoprins Did you see 404 error? Can you go to [this link](https://ibm.co/iqc2021) first and then try [the french link](https://quantum-computing.ibm.com/lab/files/quantum-challenge/2021-iqc/ex1/ex1-fr.ipynb)?

**Comment by ricardoprins** [comment]
Already did that!

**Comment by HuangJunye** [comment]
@ricardoprins did it work?

**Comment by ricardoprins** [comment]
No, this is why I'm raising this issue - Japanese and Korean versions work, but not French

**Comment by ricardoprins** [comment]
Another thing - I thought I had sent it in #10 but the language name is Français and not française - readme.md should be fixed.

**Comment by HuangJunye** [comment]
@ricardoprins I can see the French version on my Quantum Lab. Can you try again to go to this link first: ibm.co/iqc2021 and then click the link of the French notebook?

I am not sure what went wrong with the correction in #10. Could be due to other PR I merged today. I will change it later. Thanks for pointing out!

**Comment by ricardoprins** [comment]
Well, since it seems that it might be a local problem, might as well just disregard this then. I'll try to figure this out on my end.
